#!/bin/bash

# Read login and password from the S02blctl.args file
IFS=' ' read -r ssid password <<< "$(head -n 1 /etc/init.d/S02blctl.args)"

# If the password is not provided, set it to an empty string
password=${2:-"$password"}

# Connect to the specified Wi-Fi network
blctl connect_ap "$ssid" "$password"

# Wait until the connection is established
sleep 4s

# Configure IP address using udhcpc
udhcpc -i bleth0
