#!/bin/bash

# Check if the required argument (SSID) is provided
if [ -z "$1" ]; then
 echo "Usage: $0 <SSID> [PASSWORD]"
 exit 1
fi

# Assign the first argument to the variable ssid
ssid=$1

# If the second argument (PASSWORD) is provided, assign it to the variable password
password=""
if [ -n "$2" ]; then
 password=$2
fi

# Connect to the specified Wi-Fi network
bclt connect_ap "$ssid" "$password"

# Wait until the connection is established
sleep 2s

# Configure IP address using udhcpc
udhcpc -i bleth0
